/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/published-labs/{labId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublishedLabsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LabsController_findAll"];
        put?: never;
        post: operations["LabsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{labId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LabsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["LabsController_remove"];
        options?: never;
        head?: never;
        patch: operations["LabsController_update"];
        trace?: never;
    };
    "/labs/{labId}/versions/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LabVersionsController_createDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{labId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LabVersionsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{labId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LabVersionsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["LabVersionsController_patchDraft"];
        trace?: never;
    };
    "/labs/{labId}/versions/{versionId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LabVersionsController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labs/{labId}/versions/{versionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LabVersionsController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LabEmbedsController_findAll"];
        put?: never;
        post: operations["LabEmbedsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeds/{embedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["LabEmbedsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ComparatorDto: {
            /** @enum {string} */
            kind: "deepEqual" | "strictEqual" | "numberTolerance" | "stringNormalized" | "custom";
            tolerance?: number;
            normalizeWhitespace?: boolean;
            ignoreCase?: boolean;
            customComparatorId?: string;
        };
        LabTestCaseDto: {
            _id?: string;
            name: string;
            /** @enum {string} */
            kind: "io" | "unit";
            input?: (string | number | boolean | unknown[] | {
                [key: string]: unknown;
            }) | null;
            expected?: (string | number | boolean | unknown[] | {
                [key: string]: unknown;
            }) | null;
            comparator?: components["schemas"]["ComparatorDto"];
            testCode?: string;
            /** @enum {string} */
            framework?: "jest" | "vitest";
        };
        PublishedLabDto: {
            labId: string;
            versionId: string;
            versionNumber: number;
            title: string;
            /** @enum {string} */
            difficulty?: "intro" | "easy" | "medium" | "hard";
            /** @enum {string} */
            language: "javascript" | "typescript";
            promptMarkdown: string;
            hints: string[];
            starterCode: string;
            sampleTests: components["schemas"]["LabTestCaseDto"][];
            entryFnName?: string;
        };
        CreateLabDto: {
            workshopId: string;
            workshopDocumentGroupId?: string;
            slug: string;
            title: string;
            summary?: string;
            /** @default [] */
            tags: string[];
            /** @enum {string} */
            difficulty?: "intro" | "easy" | "medium" | "hard";
            estimatedMinutes?: number;
            /**
             * @default draft
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            createdBy: string;
            updatedBy?: string;
        };
        HandsOnLabMongo: {
            _id: string;
            workshopId: string;
            workshopDocumentGroupId?: string;
            slug: string;
            title: string;
            summary?: string;
            tags: string[];
            /** @enum {string} */
            difficulty?: "intro" | "easy" | "medium" | "hard";
            estimatedMinutes?: number;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            currentDraftVersionId?: string;
            latestPublishedVersionId?: string;
            createdAt: string;
            createdBy: string;
            updatedAt: string;
            updatedBy: string;
            archivedAt?: string;
            archivedBy?: string;
        };
        UpdateLabDto: {
            workshopDocumentGroupId?: string;
            slug?: string;
            title?: string;
            summary?: string;
            /** @default [] */
            tags: string[];
            /** @enum {string} */
            difficulty?: "intro" | "easy" | "medium" | "hard";
            estimatedMinutes?: number;
            updatedBy?: string;
        };
        ReferenceSolutionDto: {
            code: string;
            notesMarkdown?: string;
        };
        LabRunnerConfigDto: {
            timeoutMs: number;
            memoryMb?: number;
            entryFnName?: string;
            nodeVersion?: string;
        };
        CreateDraftVersionDto: {
            /** @enum {string} */
            language?: "typescript" | "javascript";
            promptMarkdown?: string;
            hints?: string[];
            starterCode?: string;
            referenceSolution?: components["schemas"]["ReferenceSolutionDto"];
            sampleTests?: components["schemas"]["LabTestCaseDto"][];
            hiddenTests?: components["schemas"]["LabTestCaseDto"][];
            runner?: components["schemas"]["LabRunnerConfigDto"];
            contentHash?: string;
            createdBy: string;
        };
        HandsOnLabVersionMongo: {
            _id: string;
            labId: string;
            versionNumber: number;
            isDraft: boolean;
            /** @enum {string} */
            language: "typescript" | "javascript";
            promptMarkdown: string;
            hints?: string[];
            starterCode: string;
            referenceSolution?: components["schemas"]["ReferenceSolutionDto"];
            sampleTests: components["schemas"]["LabTestCaseDto"][];
            hiddenTests: components["schemas"]["LabTestCaseDto"][];
            runner: components["schemas"]["LabRunnerConfigDto"];
            publishedAt?: string;
            publishedBy?: string;
            createdAt: string;
            createdBy: string;
            contentHash?: string;
        };
        UpdateDraftVersionDto: {
            /** @enum {string} */
            language?: "typescript" | "javascript";
            promptMarkdown?: string;
            hints?: string[];
            starterCode?: string;
            referenceSolution?: components["schemas"]["ReferenceSolutionDto"];
            sampleTests?: components["schemas"]["LabTestCaseDto"][];
            hiddenTests?: components["schemas"]["LabTestCaseDto"][];
            runner?: components["schemas"]["LabRunnerConfigDto"];
            contentHash?: string;
            createdBy?: string;
            /** @description Hash from the loaded draft; prevents stale overwrites */
            expectedContentHash: string;
        };
        TestResultDto: {
            name: string;
            /** @enum {string} */
            suite: "sample" | "hidden";
            /** @enum {string} */
            status: "passed" | "failed" | "error" | "timeout";
            durationMs: number;
            actual?: (string | number | boolean | unknown[] | {
                [key: string]: unknown;
            }) | null;
            expected?: (string | number | boolean | unknown[] | {
                [key: string]: unknown;
            }) | null;
            message?: string;
        };
        VerificationDto: {
            passed: boolean;
            contentHash: string;
            totalTests: number;
            passedTests: number;
            durationMs: number;
            results: components["schemas"]["TestResultDto"][];
        };
        PublishVersionDto: {
            expectedContentHash: string;
            publishedBy: string;
            notes?: string;
        };
        CreateEmbedDto: {
            labId: string;
            workshopId: string;
            workshopDocumentId: string;
            blockId: string;
            /**
             * @default handsOnLab
             * @enum {string}
             */
            blockType: "handsOnLab";
            pinnedVersionId?: string;
            createdBy: string;
        };
        HandsOnLabEmbedMongo: {
            _id: string;
            labId: string;
            workshopId: string;
            workshopDocumentId: string;
            blockId: string;
            blockType: string;
            pinnedVersionId?: string;
            createdAt: string;
            createdBy: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PublishedLabsController_get: {
        parameters: {
            query?: {
                versionId?: string;
            };
            header?: never;
            path: {
                labId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedLabDto"];
                };
            };
        };
    };
    LabsController_findAll: {
        parameters: {
            query?: {
                workshopId?: string;
                status?: string;
                tag?: string;
                q?: string;
                limit?: number;
                skip?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabMongo"][];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabMongo"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabMongo"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLabDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabMongo"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabVersionsController_createDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftVersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabVersionMongo"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabVersionsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabVersionMongo"][];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabVersionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabVersionMongo"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabVersionsController_patchDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDraftVersionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabVersionMongo"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabVersionsController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationDto"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabVersionsController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishVersionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabVersionMongo"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabEmbedsController_findAll: {
        parameters: {
            query?: {
                labId?: string;
                workshopId?: string;
                workshopDocumentId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabEmbedMongo"][];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabEmbedsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmbedDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandsOnLabEmbedMongo"];
                };
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LabEmbedsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                embedId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Valid platform authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrator role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
